version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: chatroulettebot-pg
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    restart: 'unless-stopped'
    ports:
      - 5432:5432